import type { Metadata } from 'next'
import {Urbanist} from 'next/font/google'
import './globals.css'
import Header from '@/components/Header'

const urbanist = Urbanist({ subsets: ['latin'],weight:['300', '900'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${urbanist.className} w-full bg-main-bg text-darkText`}>
        <Header/>
        {children}
      </body>
    </html>
  )
}
